#!/usr/bin/env python3
"""
Turn web/index.html into the C string webui.c serves.

One line of HTML becomes one line of C, so a diff of the generated header
still reads like a diff of the page.

    python3 tools/mkassets.py
"""
import sys, os

src = os.path.join(os.path.dirname(__file__), '..', 'web', 'index.html')
dst = os.path.join(os.path.dirname(__file__), '..', 'src', 'webui_assets.h')

text = open(src, encoding='utf-8').read()
if '\r' in text:
    sys.stderr.write('web/index.html has CRLF line endings; convert to LF\n')
    sys.exit(1)

out = ['/*',
       ' * webui_assets.h -- generated by tools/mkassets.py from web/index.html.',
       ' * Do not edit; edit the page and regenerate.',
       ' */',
       '#ifndef ELPIS_WEBUI_ASSETS_H',
       '#define ELPIS_WEBUI_ASSETS_H',
       '',
       'static const char elpis_webui_page[] =']
for line in text.splitlines():
    esc = line.replace('\\', '\\\\').replace('"', '\\"')
    out.append('    "%s\\n"' % esc)
out += [';', '', '#endif /* ELPIS_WEBUI_ASSETS_H */', '']
open(dst, 'w', encoding='utf-8').write('\n'.join(out))
print('%s: %d bytes from %d lines' % (dst, len(text), len(text.splitlines())))
